<?php
__( 'Radio Station', 'radio-station' );
__( 'Export Playlists', 'radio-station' );
__( 'Episodes', 'radio-station' );
__( 'Episode Information', 'radio-station' );
__( 'Select Show', 'radio-station') );
__( 'Draft', 'radio-station' );
__( 'No Shows to Select.', 'radio-station' );
__( 'Episode Number', 'radio-station' );
__( 'Episode Date', 'radio-station' );
__( 'Hosts', 'radio-station' );
__( 'Host User', 'radio-station' );
__( 'Producers', 'radio-station' );
__( 'Producer User', 'radio-station' );
__( 'Radio Station needs to be installed and activated to use Radio Station Pro.', 'radio-station' );
__( 'Your Radio Station plugin needs to updated to work with Radio Station Pro.', 'radio-station' );
__( 'The required minimum version of Radio Station plugin is:', 'radio-station' );
__( 'You do not have permission to do that.', 'radio-station' );
__( 'this is a success message', 'radio-station' );
__( 'this is a failure message', 'radio-station' );
__( 'Please upload a valid YAML file.', 'radio-station' );
__( 'Please upload a valid YAML file' );
__( 'Please upload a file to import.', 'radio-station' );
__( 'Please upload a file to import' );
__( 'Successfully parsed and imported YAML file, deleting pre-existing show data.', 'radio-station' );
__( 'Successfully parsed and imported YAML file. Pre-existing show data remains unchanged.', 'radio-station' );
__( 'Export successful. Use the following link(s) to download your data.', 'radio-station' );
__( 'Data file', 'radio-station' );
__( 'Image zip file', 'radio-statoin' );
__( 'Image tgz file', 'radio-station' );
__( 'Download one of the image files and the data file. See help for details on how to stage an import including images.', 'radio-station' );
__( 'Show data file (YAML)', 'radio-station' );
__( 'Images <strong>not</strong> exported. See help for details on how to include images.', 'radio-station' );
__( 'YAML import error. See below for details.', 'radio-station' );
__( 'Failed to create export folder', 'radio-station' );
__( 'No image exported for', 'radio-station' );
__( 'Failed to copy file. See below for details', 'radio-station' );
__( 'Failed to create show_images.zip', 'radio-station' );
__( 'Each show in the YAML file must define at minimum the following keys: ' , 'radio-station' );
__( 'show-title: may not be null.', 'radio-station' );
__( 'show-description: may not be null.', 'radio-station' );
__('show-image: must be a URL reference to an existing image.', 'radio-station' );
__( 'show-avatar: must be a URL reference to an existing image.', 'radio-station' );
__( 'show-header: must be a URL reference to an existing image.', 'radio-station' );
__( 'upload-images: may not be null.', 'radio-station' );
__( 'show-url: must be a valid web address.', 'radio-station' );
__('show-podcast: must be a valid web address.', 'radio-station' );
__( 'show-user-list: must be a simple array of valid email addresses.', 'radio-station' );
__( 'show-producer-list: must be a simple array of valid email addresses.', 'radio-station' );
__( 'show-email: must be a valid email address.', 'radio-station' );
__( 'show-active: may not be null.', 'radio-station' );
__( 'YAML data parsed successfully, but contains formatting errors. See below for details.', 'radio-station' );
__( 'Data file errors noted as follows:', 'radio-station' );
__( 'show-schedule[<weekday>] time blocks must be in 24h format and have the form "04:55" (note 0 padding).', 'radio-station' );
__( 'Error, for show-schedule[<weekday>], only "disabled" and "encore" flags are allowed', 'radio-station' );
__( 'show-schedule[<weekday>] must reference an array of time blocks containing at least one element.', 'radio-station' );
__( 'Invalid weekday. show-schedule[<weekday>] must be one of "sun".."sat", or "sunday".."saturday" (case insensitive).', 'radio-station' );
__(' show-schedule: must define at least one weekday.', 'radio-station' );
__( 'Import/Export Show Data', 'radio-station' );
__( 'Import/Export', 'radio-station' );
__( 'Import', 'radio-station' );
__( 'Import show data from a YAML file.', 'radio-station' );
__('Delete existing show data', 'radio-station' );
__( 'WARNING', 'radio-station' );
__('Import', 'radio-station' );
__( 'Export', 'radio-station' );
__( 'Export show data to a downloadable file. Does not include images by default. Check Advanced for additional options.', 'radio-station' );
__( 'Advanced', 'radio-station' );
__( 'YAML file name', 'radio-station' );
__('Default similar to', 'radio-station') );
__( 'URL where show images will be staged for import (see help)', 'radio-station') );
__( 'Title', 'radio-station' );
__( 'Episode', 'radio-station' );
__( 'Add Episode', 'radio-station' );
__( 'Edit Episode', 'radio-station' );
__( 'New Episode', 'radio-station' );
__( 'View Episode', 'radio-station' );
__( 'Search Episodes', 'radio-station' );
__( 'No Episodes found', 'radio-station' );
__( 'No Episodes found in Trash', 'radio-station' );
__( 'All Episodes', 'radio-station' );
__( 'Post Type for Show Episodes', 'radio-station' );
__( 'No Episodes were found to display.', 'radio-station' );
__( 'No Hosts were found to display.', 'radio-station' );
__( 'No Producers were found to display.', 'radio-station' );
__( 'Edit', 'radio-station' );
__( 'DJs / Hosts', 'radio-station' );
__( 'Show Editors', 'radio-station' );
__( 'Role Assignment Interface', 'radio-station' );
__( 'You can assign Radio Station roles to users directly here.', 'radio-station' );
__( 'They can also be assigned via the WordPress user editor.', 'radio-station' );
__( 'Grant Role to User', 'radio-station' );
__( 'Remove Role from User', 'radio-station' );
__( 'Visual Schedule Editor', 'radio-station' );
__( 'Table', 'radio-station' );
__( 'Tabs', 'radio-station' );
__( 'Grid', 'radio-station' );
__( 'Calendar', 'radio-station' );
__( 'You have unsaved changes. Are you sure you want to close this window?', 'radio-station' );
__( 'Save Shifts', 'radio-station' );
__( 'Save Shift', 'radio-station' );
__( 'Edit Show Shifts', 'radio-station' );
__( 'Edit Show Shift', 'radio-station' );
__( 'Add Show or Override to Schedule', 'radio-station' );
__( 'Error. Provided Show ID does not exist.', 'radio-station' );
__( 'You do not have permission to do that.', 'radio_station' );
__( 'Warning. Provided Shift ID is not valid.', 'radio-station' );
__( 'Warning. Provided Shift ID no longer exists.', 'radio-station' );
__( 'Show', 'radio-station' );
__( 'Warning! Provided Shift ID no longer exists.', 'radio-station' );
__( 'Display Shifts', 'radio-station' );
__( 'Override', 'radio-station' );
__( 'Error. Provided ID is not a Show or Override.', 'radio-station' );
__( 'Error! Invalid date value passed.', 'radio-station' );
__( 'Error! Invalid day value passed.', 'radio-station' );
__( 'Override Date', 'radio-station' );
__( 'Shift Day', 'radio-station' );
__( 'Encore', 'radio-station' );
__( 'Disabled', 'radio-station' );
__( 'Start Time', 'radio-station' );
__( 'End Time', 'radio-station' );
__( 'Shift Type', 'radio-station' );
__( 'Show Type', 'radio-station' );
__( 'Select Show...', 'radio-station' );
__( 'Open in a New Window', 'radio-station' );
__( 'Create New Show', 'radio-station' );
__( 'Override Type', 'radio-station' );
__( 'Select Override...', 'radio-station' );
__( 'Create New Override', 'radio-station' );
__( 'Error! Invalid Show ID passed.', 'radio-station' );
__( 'Error! That Show ID does not exist.', 'radio-station' );
__( 'Error! Invalid Override ID passed.', 'radio-station' );
__( 'Error! That Override ID does not exist.', 'radio-station' );
__( 'Failed. Please relogin and try again.', 'radio-station' );
__( 'View', 'radio-station' );
__( 'List', 'radio-station' );
__( 'Search Topics', 'radio-station' );
__( 'All Topics', 'radio-station' );
__( 'Parent Topic', 'radio-station' );
__( 'Parent Topic:', 'radio-station' );
__( 'Edit Topic', 'radio-station' );
__( 'Update Topic', 'radio-station' );
__( 'Add New Topic', 'radio-station' );
__( 'New Topic Name', 'radio-station' );
__( 'Topic', 'radio-station' );
__( 'Search Guests', 'radio-station' );
__( 'All Guests', 'radio-station' );
__( 'Parent Guest', 'radio-station' );
__( 'Parent Guest:', 'radio-station' );
__( 'Edit Guest', 'radio-station' );
__( 'Update Guest', 'radio-station' );
__( 'Add New Guest', 'radio-station' );
__( 'New Guest Name', 'radio-station' );
__( 'Guest', 'radio-station' );
__( 'Image', 'radio-station' );
__( 'Add Genre Image', 'radio-station' );
__( 'Remove Genre Image', 'radio-station' );
__( 'Insert', 'radio-station' );
__( 'Change Timezone', 'radio-station' );
__( 'Select Region...', 'radio-station' );
__( 'Select Timezone...', 'radio-station' );
__( 'Clear', 'radio-station' );
__( 'Cancel', 'radio-station' );
__( 'Default', 'radio-station' );
__( 'On', 'radio-station' );
__( 'Off', 'radio-station' );
__( 'Automatic Reloading', 'radio-station' );
__( 'Load Schedule for Previous Week', 'radio-station' );
__( 'Load Schedule for Next Week', 'radio-station' );
__( 'Shows', 'radio-station' );
__( 'with', 'radio-station' );
__( 'and', 'radio-station' );
__( 'to', 'radio-station' );
__( 'encore airing', 'radio-station' );
__( 'Audio File', 'radio-station' );
__( 'Genres', 'radio-station' );
__( 'No Shows', 'radio-station' );
__( 'No Shows scheduled for this date.', 'radio-station' );
__( 'Previous Day', 'radio-station' );
__( 'Next Day', 'radio-station' );
__( 'Viewing', 'radio-station' );
__( 'No Shows scheduled for this day.', 'radio-station' );
