<?php
__( 'Team Archive Page', 'radio-station' );
__( 'Select the Page for displaying the Team archive list.', 'radio-station' );
__( 'Automatic Display', 'radio-station' );
__( 'Off', 'radio-station' );
__( 'List', 'radio-station' );
__( 'Grid', 'radio-station' );
__( 'Replaces selected page content with default Team Archive. Alternatively customize display using the shortcode:', 'radio-station' );
__( 'Time Spaced Grid', 'radio-station' );
__( 'Enable Grid View option for equalized time spacing and background imsges.', 'radio-station' );
__( 'Player Bar Height', 'radio-station' );
__( 'Set the height of the Sitewide Player Bar in pixels.', 'radio-station' );
__( 'Display Current Show', 'radio-station' );
__( 'Display the Current Show in the Player Bar.', 'radio-station' );
__( 'Display Now Playing', 'radio-station' );
__( 'Display the currently playing song in the Player Bar, if a supported metadata format is available. (Icy Meta, Icecast, Shoutcast 1/2, Current Playlist', 'radio-station' );
__( 'Metadata URL', 'radio-station' );
__( 'Now playing metadata is normally retrieved via the Stream URL. Use this setting if you need to provide an alternative metadata location.', 'radio-station' );
__( 'Page Load Timeout', 'teleporter' );
__( 'Number of milliseconds to wait for new Page to load before fading in anyway. Use 0 for instant display.', 'teleporter' );
__( 'Radio Station needs to be installed and activated to use %s.', 'radio-station' );
__( 'Your Radio Station plugin needs to updated to work with %s.', 'radio-station' );
__( 'The required minimum version of Radio Station plugin is:', 'radio-station' );
__( 'Settings', 'radio-station' );
__( 'Radio Station', 'radio-station' );
__( 'Export Playlists', 'radio-station' );
__( 'Account', 'radio-station' );
__( 'You have multiple conflicting versions of Radio Station Pro activated.', 'radio-station' );
__( 'Please visit your Plugins page to deactivate the incorrect one.', 'radio-station' );
__( 'Radio Station Pro', 'radio-station' );
__( 'Extending', 'radio-station' );
__( 'You do not have permission to do that.', 'radio-station' );
__( 'Important: %s continuous player bar is active.', 'radio-station' );
__( 'This overrides the page fade in, load timeout and loader bar settings here.' );
__( 'Adjust those settings via your Radio Station settings page instead.', 'radio-station' );
__( 'Guests', 'radio-station' );
__( 'Topics', 'radio-station' );
__( 'Episodes', 'radio-station' );
__( 'Episode Information', 'radio-station' );
__( 'Show', 'radio-station' );
__( 'Select Show', 'radio-station' );
__( 'Draft', 'radio-station' );
__( 'No Shows to Select.', 'radio-station' );
__( 'Media Type', 'radio-station' );
__( 'File URL', 'radio-station' );
__( 'Media Library', 'radio-station' );
__( 'Episode Number', 'radio-station' );
__( 'Current Highest', 'radio-station' );
__( 'Broadcast Date', 'radio-station' );
__( 'Broadcast Time', 'radio-station' );
__( 'Episode Length', 'radio-station' );
__( 'minutees', 'radio-station' );
__( 'Playlist', 'radio-station' );
__( 'Select Playlist', 'radio-station' );
__( 'No Playlists to Select.', 'radio-station' );
__( 'Select Audio File', 'radio-station' );
__( 'Remove Selected Audio', 'radio-station' );
__( 'Are you sure you want to remove this audio?', 'radio-station' );
__( 'Failed. Use manual Publish or Update instead.', 'radio-station' );
__( 'Expired. Publish or Update instead.', 'radio-station' );
__( 'Failed. No Episode ID provided.', 'radio-station' );
__( 'Failed. Invalid Episode ID.', 'radio-station' );
__( 'Search Topics', 'radio-station' );
__( 'All Topics', 'radio-station' );
__( 'Parent Topic', 'radio-station' );
__( 'Parent Topic:', 'radio-station' );
__( 'Edit Topic', 'radio-station' );
__( 'Update Topic', 'radio-station' );
__( 'Add New Topic', 'radio-station' );
__( 'New Topic Name', 'radio-station' );
__( 'Topic', 'radio-station' );
__( 'Search Guests', 'radio-station' );
__( 'All Guests', 'radio-station' );
__( 'Parent Guest', 'radio-station' );
__( 'Parent Guest:', 'radio-station' );
__( 'Edit Guest', 'radio-station' );
__( 'Update Guest', 'radio-station' );
__( 'Add New Guest', 'radio-station' );
__( 'New Guest Name', 'radio-station' );
__( 'Guest', 'radio-station' );
__( 'Show %s', 'radio-station' );
__( 'Episode', 'radio-station' );
__( 'Aired on', 'radio-station' );
__( 'Image', 'radio-station' );
__( 'Add Genre Image', 'radio-station' );
__( 'Remove Genre Image', 'radio-station' );
__( 'Insert', 'radio-station' );
__( 'this is a success message', 'radio-station' );
__( 'this is a failure message', 'radio-station' );
__( 'Please upload a valid YAML file.', 'radio-station' );
__( 'Please upload a valid YAML file' );
__( 'Please upload a file to import.', 'radio-station' );
__( 'Please upload a file to import' );
__( 'Successfully parsed and imported YAML file, deleting pre-existing show data.', 'radio-station' );
__( 'Successfully parsed and imported YAML file. Pre-existing show data remains unchanged.', 'radio-station' );
__( 'Export successful. Use the following link(s to download your data.', 'radio-station' );
__( 'Data file', 'radio-station' );
__( 'Image zip file', 'radio-statoin' );
__( 'Image tgz file', 'radio-station' );
__( 'Download one of the image files and the data file. See help for details on how to stage an import including images.', 'radio-station' );
__( 'Show data file (YAML', 'radio-station' );
__( 'Images <strong>not</strong> exported. See help for details on how to include images.', 'radio-station' );
__( 'YAML import error. See below for details.', 'radio-station' );
__( 'Failed to create export folder', 'radio-station' );
__( 'No image exported for', 'radio-station' );
__( 'Failed to copy file. See below for details', 'radio-station' );
__( 'Failed to create show_images.zip', 'radio-station' );
__( 'Each show in the YAML file must define at minimum the following keys: ' , 'radio-station' );
__( 'show-title: may not be null.', 'radio-station' );
__( 'show-description: may not be null.', 'radio-station' );
__( 'show-image: must be a URL reference to an existing image.', 'radio-station' );
__( 'show-avatar: must be a URL reference to an existing image.', 'radio-station' );
__( 'show-header: must be a URL reference to an existing image.', 'radio-station' );
__( 'upload-images: may not be null.', 'radio-station' );
__( 'show-url: must be a valid web address.', 'radio-station' );
__( 'show-podcast: must be a valid web address.', 'radio-station' );
__( 'show-user-list: must be a simple array of valid email addresses.', 'radio-station' );
__( 'show-producer-list: must be a simple array of valid email addresses.', 'radio-station' );
__( 'show-email: must be a valid email address.', 'radio-station' );
__( 'show-active: may not be null.', 'radio-station' );
__( 'YAML data parsed successfully, but contains formatting errors. See below for details.', 'radio-station' );
__( 'Data file errors noted as follows:', 'radio-station' );
__( 'show-schedule[<weekday>] time blocks must be in 24h format and have the form "04:55" (note 0 padding.', 'radio-station' );
__( 'Error, for show-schedule[<weekday>], only "disabled" and "encore" flags are allowed', 'radio-station' );
__( 'show-schedule[<weekday>] must reference an array of time blocks containing at least one element.', 'radio-station' );
__( 'Invalid weekday. show-schedule[<weekday>] must be one of "sun".."sat", or "sunday".."saturday" (case insensitive.', 'radio-station' );
__( ' show-schedule: must define at least one weekday.', 'radio-station' );
__( 'Import/Export Show Data', 'radio-station' );
__( 'Import/Export', 'radio-station' );
__( 'Import', 'radio-station' );
__( 'Import show data from a YAML file.', 'radio-station' );
__( 'Delete existing show data', 'radio-station' );
__( 'WARNING', 'radio-station' );
__( 'Export', 'radio-station' );
__( 'Export show data to a downloadable file. Does not include images by default. Check Advanced for additional options.', 'radio-station' );
__( 'Advanced', 'radio-station' );
__( 'YAML file name', 'radio-station' );
__( 'Default similar to', 'radio-station' );
__( 'URL where show images will be staged for import (see help', 'radio-station' );
__( 'Metadata Source', 'radio-station' );
__( 'Default Plugin Setting', 'radio-station' );
__( 'Override: Metadata On', 'radio-station' );
__( 'Override: Metadata Off', 'radio-station' );
__( 'Override: Metadata URL', 'radio-station' );
__( 'Override: Current Playlist', 'radio-station' );
__( 'Metadata Override URL', 'radio-station' );
__( 'Title', 'radio-station' );
__( 'Add Episode', 'radio-station' );
__( 'Edit Episode', 'radio-station' );
__( 'New Episode', 'radio-station' );
__( 'View Episode', 'radio-station' );
__( 'Search Episodes', 'radio-station' );
__( 'No Episodes found', 'radio-station' );
__( 'No Episodes found in Trash', 'radio-station' );
__( 'All Episodes', 'radio-station' );
__( 'Post Type for Show Episodes', 'radio-station' );
__( 'Edit Your Host Profile', 'radio-station' );
__( 'Host Profile', 'radio-station' );
__( 'Edit Your Producer Profile', 'radio-station' );
__( 'Producer Profile', 'radio-station' );
__( 'Profile Information', 'radio-station' );
__( 'Website Link', 'radio-station' );
__( '%s Email', 'radio-station' );
__( 'Show Phone', 'radio-station' );
__( 'Patreon Page ID', 'radio-station' );
__( 'Host Image', 'radio-station' );
__( 'Producer Image', 'radio-station' );
__( 'Episode Image', 'radio-station' );
__( 'Set %s Avatar Image', 'radio-station' );
__( 'Remove %s Avatar Image', 'radio-station' );
__( 'Are you sure you want to remove this image?', 'radio-station' );
__( 'Select or Upload Image' ,'radio-station' );
__( 'Use this Image', 'radio-station' );
__( 'User Save Error! The selected User is already assigned to a %s Profile.', 'radio-station' );
__( 'Hosts', 'radio-station' );
__( 'Host User', 'radio-station' );
__( 'Producers', 'radio-station' );
__( 'Producer User', 'radio-station' );
__( 'Team', 'radio-station' );
__( 'All', 'radio-station' );
__( 'Editors', 'radio-station' );
__( 'Shows', 'radio-station' );
__( 'DJs / Hosts', 'radio-station' );
__( 'Show Editors', 'radio-station' );
__( 'Role Assignment Interface', 'radio-station' );
__( 'You can assign Radio Station roles to users directly here.', 'radio-station' );
__( 'They can also be assigned via the WordPress user editor.', 'radio-station' );
__( 'Grant Role to User(s', 'radio-station' );
__( 'Remove Role from User(s', 'radio-station' );
__( 'Update User Roles', 'radio-station' );
__( 'You have unsaved role changes.', 'radio-station' );
__( 'role added to user', 'radio-station' );
__( 'role removed from user', 'radio-station' );
__( 'Visual Schedule Editor', 'radio-station' );
__( 'Table', 'radio-station' );
__( 'Tabs', 'radio-station' );
__( 'Calendar', 'radio-station' );
__( 'Your session has expired. You can log in again from this page or go to the login page.' );
__( 'You have unsaved changes. Are you sure you want to close this window?', 'radio-station' );
__( 'Save Shift', 'radio-station' );
__( 'Save Shifts', 'radio-station' );
__( 'Save Override', 'radio-station' );
__( 'Save Overrides', 'radio-station' );
__( 'Edit Show Shifts', 'radio-station' );
__( 'Edit Override Times', 'radio-station' );
__( 'Edit Show Shift', 'radio-station' );
__( 'Edit Override Time', 'radio-station' );
__( 'Add to Schedule', 'radio-station' );
__( 'Add Show or Override to Schedule', 'radio-station' );
__( 'Error. Provided Show ID does not exist.', 'radio-station' );
__( 'You do not have permission to do that.', 'radio_station' );
__( 'Warning. Provided Shift ID is not valid.', 'radio-station' );
__( 'Warning. Provided Shift ID no longer exists.', 'radio-station' );
__( 'Display Shifts', 'radio-station' );
__( 'All Show Shifts', 'radio-station' );
__( 'Warning. Provided Override Shift ID no longer exists.', 'radio-station' );
__( 'Override', 'radio-station' );
__( 'Display Override', 'radio-station' );
__( 'All Override Times', 'radio-station' );
__( 'Error. Provided ID is not a Show or Override.', 'radio-station' );
__( 'Error! Invalid date value passed.', 'radio-station' );
__( 'Error! Invalid day value passed.', 'radio-station' );
__( 'Timeslot Type', 'radio-station' );
__( 'Override Date', 'radio-station' );
__( 'Shift Day', 'radio-station' );
__( 'Encore', 'radio-station' );
__( 'Disabled', 'radio-station' );
__( 'Start Time', 'radio-station' );
__( 'End Time', 'radio-station' );
__( 'Show Type', 'radio-station' );
__( 'Override Type', 'radio-station' );
__( 'Select Show...', 'radio-station' );
__( 'Add Shift', 'radio-station' );
__( 'Select Override...', 'radio-station' );
__( 'Add Override', 'radio-station' );
__( 'Open in a New Window', 'radio-station' );
__( 'Create New Show', 'radio-station' );
__( 'Create New Override', 'radio-station' );
__( 'Adding Show Shift...', 'radio-station' );
__( 'Show Shift Added.', 'radio-station' );
__( 'Clear Shifts', 'radio-station' );
__( 'Adding Override Time...', 'radio-station' );
__( 'Override Time Saved.', 'radio-station' );
__( 'Clear Overrides', 'radio-station' );
__( 'Load Schedule for Previous Week', 'radio-station' );
__( 'Load Schedule for Next Week', 'radio-station' );
__( 'View', 'radio-station' );
__( 'No Hosts were found to display.', 'radio-station' );
__( 'No Producers were found to display.', 'radio-station' );
__( 'No Episodes were found to display.', 'radio-station' );
__( 'Published on ', 'radio-station' );
__( 'No %s were found to display.', 'radio-station' );
__( 'Social Icons', 'radio-station' );
__( 'Soundcloud', 'radio-station' );
__( 'Mixcloud', 'radio-station' );
__( 'Spotify', 'radio-station' );
__( 'Twitch', 'radio-station' );
__( 'Discord', 'radio-station' );
__( 'Facebook', 'radio-station' );
__( 'Twitter', 'radio-station' );
__( 'YouTube', 'radio-station' );
__( 'LinkedIn', 'radio-station' );
__( 'Xing', 'radio-station' );
__( 'Instagram', 'radio-station' );
__( 'WhatsApp', 'radio-station' );
__( 'Pinterest', 'radio-station' );
__( 'Custom', 'radio-station' );
__( 'Add a Social Icon', 'radio-station' );
__( 'Move this Icon Up', 'radio-station' );
__( 'Move this Icon Down', 'radio-station' );
__( 'Remove this Social Icon', 'radio-station' );
__( 'URL', 'radio-station' );
__( 'Icon URL', 'radio-station' );
__( 'Unknown', 'radio-station' );
__( 'Social URL Page Link', 'radio-station' );
__( 'Social Icon Image URL', 'radio-station' );
__( 'Are you sure you want to remove this Social Icon?', 'radio-station' );
__( 'No Social Icon Services defined.', 'radio-station' );
__( 'You can reorder this icon after saving it.', 'radio-station' );
__( 'Change Timezone', 'radio-station' );
__( 'Select Region...', 'radio-station' );
__( 'Clear', 'radio-station' );
__( 'Cancel', 'radio-station' );
__( 'Select Timezone...', 'radio-station' );
__( 'Default', 'radio-station' );
__( 'On', 'radio-station' );
__( 'Automatic Reloading', 'radio-station' );
__( 'to', 'radio-station' );
__( 'with', 'radio-station' );
__( 'and', 'radio-station' );
__( 'encore airing', 'radio-station' );
__( 'Audio File', 'radio-station' );
__( 'Genres', 'radio-station' );
__( 'No Shows', 'radio-station' );
__( 'No Shows scheduled for this date.', 'radio-station' );
__( 'Previous Day', 'radio-station' );
__( 'Next Day', 'radio-station' );
__( 'Viewing', 'radio-station' );
__( 'No Shows scheduled for this day.', 'radio-station' );
__( 'Show RSS Feed', 'radio-station' );
__( 'Become a Supporter for', 'radio-station' );
__( 'Episode Info', 'radio-station' );
__( 'Broadcasted', 'radio-station' );
__( 'on', 'radio-station' );
__( 'Hosted by', 'radio-station' );
__( 'Produced by', 'radio-station' );
__( 'Show More', 'radio-station' );
__( 'Show Less', 'radio-station' );
__( 'Listen to this %s', 'radio-station' );
__( 'Player', 'radio-station' );
__( 'Download this Episode', 'radio-station' );
__( 'About this %s', 'radio-station' );
__( 'About', 'radio-station' );
__( '%s Show', 'radio-station' );
__( '%s Playlist', 'radio-station' );
__( 'Jump to', 'radio-station' );
__( 'Visit %s Website', 'radio-station' );
__( '%s Phone Number', 'radio-station' );
__( 'Email %s', 'radio-station' );
__( '%s RSS Feed', 'radio-station' );
__( 'Download Latest Broadcast', 'radio-station' );
__( 'Profile Info', 'radio-station' );
__( 'Website', 'radio-station' );
__( 'Email', 'radio-station' );
__( 'Phone', 'radio-station' );
